[theme]
primaryColor     = "#FF43B8"
backgroundColor  = "#051832"
secondaryBackgroundColor = "#0B1B34"
textColor        = "#FFFFFF"
font             = "sans serif"

[server]
headless = true
port     = 8502

[browser]
gatherUsageStats = false
